### ISSUE TITLE
bug. I see error in traces

### ISSUE THREAD

**Issue by vistrcm** [vistrcm/apthunt#18]
fix error in traces. example
```
[WARNING]	2019-11-13T00:22:10.980Z	xxxx-xxxx-xxx-xxx	got exception doing '<function put_item at 0x7f627bf1f158>' on with '{'FeedTitle': 'simulated', 'FeedUrl': 'simulated', 'PostTitle': 'simulated', 'PostUrl': 'https://sfbay.craigslist.org/sby/apa/d/milpitas-business-center-cable-ready/7014931246.html', 'PostContent': 'simulated', 'PostPublished': 'simulated', 'added': 1573604529795, 'intid': 'd92c293b57964c69a6829357483f922e'}': 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
File "/var/task/handler.py", line 95, in handler
resp = operations[operation](payload)
File "/var/task/wrapt/wrappers.py", line 564, in __call__
args, kwargs)
File "/var/task/aws_xray_sdk/core/models/subsegment.py", line 58, in __call__
meta_processor=None,
File "/var/task/aws_xray_sdk/core/recorder.py", line 424, in record_subsegment
return_value = wrapped(*args, **kwargs)
File "/var/task/handler.py", line 153, in put_item
parsed = parse_page(post_url)
File "/var/task/wrapt/wrappers.py", line 564, in __call__
args, kwargs)
File "/var/task/aws_xray_sdk/core/models/subsegment.py", line 58, in __call__
meta_processor=None,
File "/var/task/aws_xray_sdk/core/recorder.py", line 424, in record_subsegment
return_value = wrapped(*args, **kwargs)
File "/var/task/clparser.py", line 136, in parse_page
result["notices"] = [n.text for n in userbody.find("ul.notices", first=True).find("li")]
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by vistrcm** [comment]
simple handling added in commit https://github.com/vistrcm/apthunt/commit/d3c20241f92806f320762aad85559521b25769d2
